In [2]:
import pandas as pd

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
df = pd.read_csv('500hits.csv',encoding ='latin-1')

In [5]:
df.head(2)

,PLAYER,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA,HOF
0,Ty Cobb,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,178,0.366,1
1,Stan Musial,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,31,0.331,1

In [6]:
X = df.drop(columns=['PLAYER','HOF'])

In [7]:
y = df['HOF']

In [8]:
X.head()

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA
0,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,178,0.366
1,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,31,0.331
2,22,2789,10195,1882,3514,792,222,117,724,1381,220,432,129,0.345
3,20,2747,11195,1923,3465,544,66,260,1311,1082,1840,358,97,0.310
4,21,2792,10430,1736,3430,640,252,101,0,963,327,722,15,0.329

In [9]:
X.shape

(465, 14)

In [10]:
y.shape

(465,)

In [11]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: HOF, dtype: int64

In [13]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state = 11,test_size = 0.2) # random state allows u to test with same split of test data

In [14]:
X_train.shape

(372, 14)

In [15]:
X_test.shape

(93, 14)

In [16]:
y_train.shape

(372,)

In [17]:
y_test.shape

(93,)

In [18]:
X_train.head()

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA
289,18,2028,7298,873,1993,284,40,325,1163,620,1313,20,38,0.273
288,13,1836,6826,856,1996,392,117,43,402,513,360,247,108,0.292
350,14,1799,6373,876,1854,282,64,49,630,844,627,37,51,0.291
196,17,2158,7911,1057,2276,414,92,94,844,690,784,246,138,0.288
184,19,2390,8570,1386,2369,420,65,244,1084,1197,1099,143,75,0.276

In [22]:
X_train.describe().round(3)

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA
count,372.000,372.000,372.000,372.000,372.000,372.000,372.000,372.000,372.000,372.000,372.000,372.000,372.000,372.000
mean,17.011,2046.522,7526.078,1154.126,2177.995,382.505,78.094,202.642,901.073,780.105,850.323,196.927,58.987,0.289
std,2.662,351.233,1302.406,291.308,426.615,97.173,48.798,141.726,484.370,327.453,472.918,185.586,49.322,0.021
min,11.000,1331.000,4981.000,651.000,1660.000,177.000,3.000,9.000,0.000,239.000,0.000,7.000,0.000,0.246
25%,15.000,1797.500,6507.500,936.000,1838.000,312.000,41.000,79.750,645.000,536.500,448.000,64.500,23.000,0.274
50%,17.000,1992.000,7237.000,1099.000,2080.500,367.000,67.000,185.500,977.500,719.000,844.000,141.000,52.000,0.288
75%,19.000,2245.500,8198.250,1305.000,2383.750,436.250,108.000,293.250,1218.500,961.250,1234.250,285.500,84.000,0.300
max,26.000,3308.000,12364.000,2295.000,4189.000,792.000,309.000,755.000,2297.000,2190.000,1936.000,1406.000,335.000,0.366

In [21]:
X_test.describe().round(2)

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA
count,93.00,93.00,93.00,93.00,93.00,93.00,93.00,93.00,93.00,93.00,93.00,93.00,93.00,93.00
mean,17.20,2057.41,7452.97,1135.06,2139.26,374.74,80.40,194.68,867.01,797.39,836.06,191.82,54.47,0.29
std,3.15,368.58,1265.37,283.88,415.16,93.93,51.79,151.60,495.13,328.75,552.31,166.93,42.51,0.02
min,11.00,1399.00,5472.00,601.00,1660.00,206.00,14.00,15.00,0.00,266.00,15.00,8.00,0.00,0.25
25%,15.00,1820.00,6622.00,935.00,1818.00,310.00,45.00,78.00,618.00,527.00,359.00,61.00,15.00,0.27
50%,17.00,1997.00,7359.00,1108.00,2054.00,361.00,68.00,151.00,926.00,750.00,745.00,137.00,50.00,0.28
75%,19.00,2282.00,8096.00,1283.00,2256.00,432.00,99.00,291.00,1138.00,937.00,1179.00,271.00,83.00,0.30
max,25.00,2850.00,10876.00,1859.00,3430.00,668.00,252.00,612.00,1922.00,1747.00,2597.00,744.00,173.00,0.34