In [1]:
import pandas as pd

In [2]:
d = {'sales': [100000,222000,1000000,522000,111111,222222,1111111,20000,75000,90000,1000000,10000],
'city': ['Tampa','Tampa','Orlando','Jacksonville','Miami','Jacksonville','Miami','Miami','Orlando','Orlando','Orlando','Orlando'],
'size': ['Small', 'Medium','Large','Large','Small','Medium','Large','Small','Medium','Medium','Medium','Small',]}

In [3]:
df = pd.DataFrame(d)

In [4]:
df.head()

     sales          city    size
0   100000         Tampa   Small
1   222000         Tampa  Medium
2  1000000       Orlando   Large
3   522000  Jacksonville   Large
4   111111         Miami   Small

In [5]:
# Here size is an ordinal data , now let us learn how to encode it :

In [6]:
df['size'].unique()

array(['Small', 'Medium', 'Large'], dtype=object)

In [7]:
sizes =  ["Small","Medium","Large"]

In [8]:
from sklearn.preprocessing import OrdinalEncoder

In [10]:
OE = OrdinalEncoder(categories = [sizes])

In [12]:
OE.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.]])

In [13]:
df['size'] = OE.fit_transform(df[['size']])

In [14]:
df

      sales          city  size
0    100000         Tampa   0.0
1    222000         Tampa   1.0
2   1000000       Orlando   2.0
3    522000  Jacksonville   2.0
4    111111         Miami   0.0
5    222222  Jacksonville   1.0
6   1111111         Miami   2.0
7     20000         Miami   0.0
8     75000       Orlando   1.0
9     90000       Orlando   1.0
10  1000000       Orlando   1.0
11    10000       Orlando   0.0