In [28]:
import pandas as pd

In [29]:
df = pd.read_csv("stroke.csv")

In [30]:
df.shape

(5110, 12)

In [31]:
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [32]:
df.isnull().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [33]:
df.dropna(subset=['bmi'], inplace=True)

In [34]:
df.isnull().sum()

id                   0
gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [35]:
df.dtypes

id                     int64
gender                object
age                  float64
hypertension           int64
heart_disease          int64
ever_married          object
work_type             object
Residence_type        object
avg_glucose_level    float64
bmi                  float64
smoking_status        object
stroke                 int64
dtype: object

In [38]:
df['gender'] = df['gender'].astype(str)

In [49]:
df['smoking_status'] = df['smoking_status'].astype(str)

In [50]:
df.dtypes

id                   float64
age                  float64
hypertension         float64
heart_disease        float64
work_type             object
Residence_type        object
avg_glucose_level    float64
bmi                  float64
smoking_status        object
stroke               float64
gender_Female        float64
gender_Male          float64
gender_Other         float64
dtype: object

In [40]:
from sklearn.preprocessing import OneHotEncoder

In [42]:
ohe = OneHotEncoder(sparse_output=False)

In [43]:
encoded = ohe.fit_transform(df[['gender']])

In [44]:
encoded_df = pd.DataFrame(encoded, columns=ohe.get_feature_names_out(['gender']))

In [45]:
df = pd.concat([df.drop('gender', axis=1), encoded_df], axis=1)

In [46]:
df.head()

,id,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke,gender_Female,gender_Male,gender_Other
0,9046.0,67.0,0.0,1.0,Yes,Private,Urban,228.69,36.6,formerly smoked,1.0,0.0,1.0,0.0
2,31112.0,80.0,0.0,1.0,Yes,Private,Rural,105.92,32.5,never smoked,1.0,1.0,0.0,0.0
3,60182.0,49.0,0.0,0.0,Yes,Private,Urban,171.23,34.4,smokes,1.0,1.0,0.0,0.0
4,1665.0,79.0,1.0,0.0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1.0,0.0,1.0,0.0
5,56669.0,81.0,0.0,0.0,Yes,Private,Urban,186.21,29.0,formerly smoked,1.0,0.0,1.0,0.0

In [48]:
df = df.drop(columns = ['ever_married'])

In [53]:
encoded1 = ohe.fit_transform(df[['smoking_status']])
encoded1_df = pd.DataFrame(encoded1, columns=ohe.get_feature_names_out(['smoking_status']))
df = pd.concat([df.drop('smoking_status', axis=1), encoded1_df], axis=1)

In [54]:
df.head()

,id,age,hypertension,heart_disease,work_type,Residence_type,avg_glucose_level,bmi,stroke,gender_Female,gender_Male,gender_Other,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_nan,smoking_status_never smoked,smoking_status_smokes
0,9046.0,67.0,0.0,1.0,Private,Urban,228.69,36.6,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
2,31112.0,80.0,0.0,1.0,Private,Rural,105.92,32.5,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,60182.0,49.0,0.0,0.0,Private,Urban,171.23,34.4,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1665.0,79.0,1.0,0.0,Self-employed,Rural,174.12,24.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
5,56669.0,81.0,0.0,0.0,Private,Urban,186.21,29.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [55]:
df['work_type'].unique()

array(['Private', 'Self-employed', 'Govt_job', 'children', 'Never_worked',
       nan], dtype=object)

In [56]:
df['work_type'] = df['work_type'].astype(str)
encoded2 = ohe.fit_transform(df[['work_type']])
encoded2_df = pd.DataFrame(encoded2, columns=ohe.get_feature_names_out(['work_type']))
df = pd.concat([df.drop('work_type', axis=1), encoded2_df], axis=1)

In [57]:
df.head()

,id,age,hypertension,heart_disease,Residence_type,avg_glucose_level,bmi,stroke,gender_Female,gender_Male,...,smoking_status_formerly smoked,smoking_status_nan,smoking_status_never smoked,smoking_status_smokes,work_type_Govt_job,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,work_type_nan
0,9046.0,67.0,0.0,1.0,Urban,228.69,36.6,1.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,31112.0,80.0,0.0,1.0,Rural,105.92,32.5,1.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
3,60182.0,49.0,0.0,0.0,Urban,171.23,34.4,1.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,1665.0,79.0,1.0,0.0,Rural,174.12,24.0,1.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
5,56669.0,81.0,0.0,0.0,Urban,186.21,29.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [58]:
df.drop(columns = ['Residence_type'])

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke,gender_Female,gender_Male,gender_Other,...,smoking_status_formerly smoked,smoking_status_nan,smoking_status_never smoked,smoking_status_smokes,work_type_Govt_job,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,work_type_nan
0,9046.0,67.0,0.0,1.0,228.69,36.6,1.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,31112.0,80.0,0.0,1.0,105.92,32.5,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
3,60182.0,49.0,0.0,0.0,171.23,34.4,1.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,1665.0,79.0,1.0,0.0,174.12,24.0,1.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
5,56669.0,81.0,0.0,0.0,186.21,29.0,1.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5039,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
5048,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
5093,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
5099,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
5105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,1.0

In [59]:
df.isnull().sum()

id                                201
age                               201
hypertension                      201
heart_disease                     201
Residence_type                    201
avg_glucose_level                 201
bmi                               201
stroke                            201
gender_Female                     201
gender_Male                       201
gender_Other                      201
smoking_status_Unknown              9
smoking_status_formerly smoked      9
smoking_status_nan                  9
smoking_status_never smoked         9
smoking_status_smokes               9
work_type_Govt_job                  1
work_type_Never_worked              1
work_type_Private                   1
work_type_Self-employed             1
work_type_children                  1
work_type_nan                       1
dtype: int64

In [60]:
df.dropna()

,id,age,hypertension,heart_disease,Residence_type,avg_glucose_level,bmi,stroke,gender_Female,gender_Male,...,smoking_status_formerly smoked,smoking_status_nan,smoking_status_never smoked,smoking_status_smokes,work_type_Govt_job,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,work_type_nan
0,9046.0,67.0,0.0,1.0,Urban,228.69,36.6,1.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,31112.0,80.0,0.0,1.0,Rural,105.92,32.5,1.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
3,60182.0,49.0,0.0,0.0,Urban,171.23,34.4,1.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,1665.0,79.0,1.0,0.0,Rural,174.12,24.0,1.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
5,56669.0,81.0,0.0,0.0,Urban,186.21,29.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4904,22417.0,5.0,0.0,0.0,Rural,80.93,24.8,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4905,49925.0,60.0,0.0,0.0,Rural,84.54,23.4,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4906,72696.0,53.0,0.0,0.0,Urban,70.51,54.1,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4907,39708.0,55.0,0.0,0.0,Rural,56.87,28.9,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4908,60426.0,69.0,0.0,0.0,Urban,67.55,38.1,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [61]:
df.isnull().sum()

id                                201
age                               201
hypertension                      201
heart_disease                     201
Residence_type                    201
avg_glucose_level                 201
bmi                               201
stroke                            201
gender_Female                     201
gender_Male                       201
gender_Other                      201
smoking_status_Unknown              9
smoking_status_formerly smoked      9
smoking_status_nan                  9
smoking_status_never smoked         9
smoking_status_smokes               9
work_type_Govt_job                  1
work_type_Never_worked              1
work_type_Private                   1
work_type_Self-employed             1
work_type_children                  1
work_type_nan                       1
dtype: int64

In [62]:
df = df.dropna()

In [63]:
df.head()

,id,age,hypertension,heart_disease,Residence_type,avg_glucose_level,bmi,stroke,gender_Female,gender_Male,...,smoking_status_formerly smoked,smoking_status_nan,smoking_status_never smoked,smoking_status_smokes,work_type_Govt_job,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,work_type_nan
0,9046.0,67.0,0.0,1.0,Urban,228.69,36.6,1.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,31112.0,80.0,0.0,1.0,Rural,105.92,32.5,1.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
3,60182.0,49.0,0.0,0.0,Urban,171.23,34.4,1.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,1665.0,79.0,1.0,0.0,Rural,174.12,24.0,1.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
5,56669.0,81.0,0.0,0.0,Urban,186.21,29.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [64]:
df.isnull().sum()

id                                0
age                               0
hypertension                      0
heart_disease                     0
Residence_type                    0
avg_glucose_level                 0
bmi                               0
stroke                            0
gender_Female                     0
gender_Male                       0
gender_Other                      0
smoking_status_Unknown            0
smoking_status_formerly smoked    0
smoking_status_nan                0
smoking_status_never smoked       0
smoking_status_smokes             0
work_type_Govt_job                0
work_type_Never_worked            0
work_type_Private                 0
work_type_Self-employed           0
work_type_children                0
work_type_nan                     0
dtype: int64

In [65]:
from sklearn.neighbors import KNeighborsClassifier

In [66]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,classification_report

In [67]:
df.shape

(4717, 22)

In [68]:
for i, col in enumerate(df.columns):
    print(i, col)

0 id
1 age
2 hypertension
3 heart_disease
4 Residence_type
5 avg_glucose_level
6 bmi
7 stroke
8 gender_Female
9 gender_Male
10 gender_Other
11 smoking_status_Unknown
12 smoking_status_formerly smoked
13 smoking_status_nan
14 smoking_status_never smoked
15 smoking_status_smokes
16 work_type_Govt_job
17 work_type_Never_worked
18 work_type_Private
19 work_type_Self-employed
20 work_type_children
21 work_type_nan

In [78]:
y = df.iloc[:, 7]

In [79]:
X = pd.concat([df.iloc[:, :7], df.iloc[:, 8:]], axis=1)

In [80]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.2, random_state = 20)

In [81]:
scaler = MinMaxScaler(feature_range = (0,1))

In [82]:
df['Residence_type'] = df['Residence_type'].map({'Urban':1, 'Rural':0})

In [77]:
df.dtypes

id                                float64
age                               float64
hypertension                      float64
heart_disease                     float64
Residence_type                      int64
avg_glucose_level                 float64
bmi                               float64
stroke                            float64
gender_Female                     float64
gender_Male                       float64
gender_Other                      float64
smoking_status_Unknown            float64
smoking_status_formerly smoked    float64
smoking_status_nan                float64
smoking_status_never smoked       float64
smoking_status_smokes             float64
work_type_Govt_job                float64
work_type_Never_worked            float64
work_type_Private                 float64
work_type_Self-employed           float64
work_type_children                float64
work_type_nan                     float64
dtype: object

In [83]:
X_train = scaler.fit_transform(X_train)

In [84]:
X_test = scaler.fit_transform(X_test)

In [85]:
knn = KNeighborsClassifier(n_neighbors = 8)

In [86]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=8)

In [87]:
y_pred = knn.predict(X_test)

In [88]:
y_pred

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [89]:
knn.score(X_test, y_test)

0.9502118644067796

In [90]:
cm = confusion_matrix(y_test, y_pred)

In [91]:
cm

array([[897,   0],
       [ 47,   0]])

In [92]:
y.value_counts()

stroke
0.0    4508
1.0     209
Name: count, dtype: int64