In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("500hits.csv" , encoding = "latin-1")

In [3]:
df.head()

,PLAYER,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA,HOF
0,Ty Cobb,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,178,0.366,1
1,Stan Musial,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,31,0.331,1
2,Tris Speaker,22,2789,10195,1882,3514,792,222,117,724,1381,220,432,129,0.345,1
3,Derek Jeter,20,2747,11195,1923,3465,544,66,260,1311,1082,1840,358,97,0.310,1
4,Honus Wagner,21,2792,10430,1736,3430,640,252,101,0,963,327,722,15,0.329,1

In [4]:
df = df.drop(columns= ["PLAYER","CS"])

In [5]:
df.head()

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,BA,HOF
0,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,0.366,1
1,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,0.331,1
2,22,2789,10195,1882,3514,792,222,117,724,1381,220,432,0.345,1
3,20,2747,11195,1923,3465,544,66,260,1311,1082,1840,358,0.310,1
4,21,2792,10430,1736,3430,640,252,101,0,963,327,722,0.329,1

In [6]:
df.describe().round(2)

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,BA,HOF
count,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00
mean,17.05,2048.70,7511.46,1150.31,2170.25,380.95,78.55,201.05,894.26,783.56,847.47,195.91,0.29,0.33
std,2.77,354.39,1294.07,289.64,424.19,96.48,49.36,143.62,486.19,327.43,489.22,181.85,0.02,0.47
min,11.00,1331.00,4981.00,601.00,1660.00,177.00,3.00,9.00,0.00,239.00,0.00,7.00,0.25,0.00
25%,15.00,1802.00,6523.00,936.00,1838.00,312.00,41.00,79.00,640.00,535.00,436.00,63.00,0.27,0.00
50%,17.00,1993.00,7241.00,1104.00,2076.00,366.00,67.00,178.00,968.00,736.00,825.00,137.00,0.29,0.00
75%,19.00,2247.00,8180.00,1296.00,2375.00,436.00,107.00,292.00,1206.00,955.00,1226.00,285.00,0.30,1.00
max,26.00,3308.00,12364.00,2295.00,4189.00,792.00,309.00,755.00,2297.00,2190.00,2597.00,1406.00,0.37,2.00

In [7]:
# X1 = df.iloc[:,0:13]

In [24]:
X2 = df.iloc[:,0:13]

In [25]:
from sklearn.preprocessing import StandardScaler

In [26]:
stand_scale = StandardScaler()

In [27]:
X2 = stand_scale.fit_transform(X2)

In [30]:
X2 = pd.DataFrame(X2)

In [31]:
X2.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,2.516295,2.786078,3.034442,3.787062,4.764193,3.559333,4.389485,-0.585841,-0.346449,1.423013,-1.003628,3.832067,3.648290
1,1.792237,2.760655,2.677044,2.760530,3.444971,3.569709,1.996457,1.909487,2.175837,2.493089,-0.309948,-0.649080,1.996159
2,1.792237,2.091184,2.075964,2.528955,3.171214,4.264876,2.909053,-0.585841,-0.350567,1.826585,-1.283965,1.299723,2.657012
3,1.068180,1.972543,2.849554,2.670665,3.055576,1.691719,-0.254611,0.410896,0.858071,0.912434,2.030966,0.892346,1.004881
4,1.430208,2.099658,2.257758,2.024329,2.972977,2.687780,3.517449,-0.697364,-1.841290,0.548609,-1.065016,2.896201,1.901752

In [32]:
X2.describe().round(2)

,0,1,2,3,4,5,6,7,8,9,10,11,12
count,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00
mean,-0.00,0.00,0.00,0.00,0.00,0.00,-0.00,-0.00,0.00,0.00,-0.00,0.00,0.00
std,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
min,-2.19,-2.03,-1.96,-1.90,-1.20,-2.12,-1.53,-1.34,-1.84,-1.66,-1.73,-1.04,-2.02
25%,-0.74,-0.70,-0.76,-0.74,-0.78,-0.72,-0.76,-0.85,-0.52,-0.76,-0.84,-0.73,-0.74
50%,-0.02,-0.16,-0.21,-0.16,-0.22,-0.16,-0.23,-0.16,0.15,-0.15,-0.05,-0.32,-0.08
75%,0.71,0.56,0.52,0.50,0.48,0.57,0.58,0.63,0.64,0.52,0.77,0.49,0.53
max,3.24,3.56,3.75,3.96,4.76,4.26,4.67,3.86,2.89,4.30,3.58,6.66,3.65

In [33]:
##NORMALIZATION  ---> sd = 1 , mean = 0

In [34]:
Y2 = df.iloc[:,0:13]

In [35]:
from sklearn.preprocessing import MinMaxScaler

In [38]:
Min_scale= MinMaxScaler(feature_range=(0,1))

In [39]:
Y2 = Min_scale.fit_transform(Y2)

In [40]:
Y2 = pd.DataFrame(Y2)

In [41]:
Y2.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,0.866667,0.861912,0.874035,0.971074,1.000000,0.889431,0.954248,0.144772,0.316064,0.517683,0.137466,0.632595,1.000000
1,0.733333,0.857360,0.811459,0.795750,0.778964,0.891057,0.568627,0.624665,0.849369,0.697078,0.268002,0.050751,0.708333
2,0.733333,0.737481,0.706217,0.756198,0.733096,1.000000,0.715686,0.144772,0.315194,0.585341,0.084713,0.303788,0.825000
3,0.600000,0.716237,0.841663,0.780401,0.713721,0.596748,0.205882,0.336461,0.570744,0.432086,0.708510,0.250893,0.533333
4,0.666667,0.738998,0.738047,0.670012,0.699881,0.752846,0.813725,0.123324,0.000000,0.371092,0.125915,0.511079,0.691667

In [42]:
Y2.describe().round(2)

,0,1,2,3,4,5,6,7,8,9,10,11,12
count,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00
mean,0.40,0.36,0.34,0.32,0.20,0.33,0.25,0.26,0.39,0.28,0.33,0.14,0.36
std,0.18,0.18,0.18,0.17,0.17,0.16,0.16,0.19,0.21,0.17,0.19,0.13,0.18
min,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,0.27,0.24,0.21,0.20,0.07,0.22,0.12,0.09,0.28,0.15,0.17,0.04,0.23
50%,0.40,0.33,0.31,0.30,0.16,0.31,0.21,0.23,0.42,0.25,0.32,0.09,0.34
75%,0.53,0.46,0.43,0.41,0.28,0.42,0.34,0.38,0.53,0.37,0.47,0.20,0.45
max,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00